### ISSUE TITLE
Obsolete documentation

### ISSUE THREAD

**Issue by addman2** [azadoks/aiida-basis#1]
Hello,

I believe there is obsolete documentation.

Command `aiida-basis  install sto-g3` does not work. I believe it should be `aiida-basis  install basisset`. However, is it possible to fetch the basis set directly from BSE? The help shows, there is options only to load basis from archive formats.

Best,

Otto

**Comment by azadoks** [comment]
Hi Otto,

Thanks for the feedback!
I haven't updated the readme in a long time (looks like 7 months), and the badges were still pointing to `aiida-pseudo` 😅.

Currently, BSE basis sets are not supported, although the support shouldn't be too difficult to implement once an appropriate AiiDA data type is implemented for Gaussian/Slater/etc. type orbital bases.

This is still an open question as to what the implementation should be like.
For OpenMX PAOs, it makes sense to store the basis set as a collection of files (as is done in `aiida-pseudo` for pseudopotentials), but this is probably not true for the basis sets on the BSE.

I'll make an issue where this implementation can be discussed, and once we have a working `Data` type for storing BSE basis sets in AiiDA, implementing an installer should be fairly straightforward.

I've updated the readme to better reflect the state of the project.

Cheers,
Austin
